### ISSUE TITLE
Handle event handlers in the script file

### ISSUE THREAD

**Issue by joostf** [DaanKorver/fdnd-squad-page-bra1n#14]
https://github.com/DaanKorver/fdnd-squad-page-bra1n/blob/8709ac18fcc2ca42b27e4ec8dec24b7f42899266/index.html#L29-L33

not inline in HTML

**Comment by DaanKorver** [comment]
removed the inline event handlers.
For reference see:
https://github.com/DaanKorver/fdnd-squad-page-bra1n/commit/0fb332facc1bb5668fe77f69f54227561e675968
and
https://github.com/DaanKorver/fdnd-squad-page-bra1n/commit/a734a053c7ec48bf63172affbf3cb201aba31936
