### ISSUE TITLE
script tag in head section with defer?

### ISSUE THREAD

**Issue by joostf** [DaanKorver/fdnd-squad-page-bra1n#15]
https://github.com/DaanKorver/fdnd-squad-page-bra1n/blob/8709ac18fcc2ca42b27e4ec8dec24b7f42899266/index.html#L43

**Comment by DaanKorver** [comment]
Fixed :D

https://github.com/DaanKorver/fdnd-squad-page-bra1n/commit/8f250259e2b0b9c675f4e22fe551bff3e3341c7a
